const AuthActionTypes={
    SIGNIN_START:"SIGNIN_START",
    SIGNIN_SUCCESSFUL:"SIGNIN_SUCCESSFUL",
    SIGNIN_FAILURE:"SIGNIN_FAILURE",
    SIGNUP_START:"SIGNUP_START",
    SIGNUP_SUCCESSFUL:"SIGNUP_SUCCESSFUL",
    SIGNUP_FAILURE:"SIGNUP_FAILURE",
    LOGOUT_START:"LOGOUT_START",
    LOGOUT_SUCCESSFUL:"LOGOUT_SUCCESSFUL",
    LOGOUT_FAILURE:"LOGOUT_FAILURE",
    GET_USER_DETAILS:"GET_USER_DETAILS",
    SET_USER_DETAILS:"SET_USER_DETAILS",
    SET_IS_REGISTERED_FALSE:"SET_IS_REGISTERED_FALSE"
}

export default AuthActionTypes