const networkActionTypes={
    GET_REQUESTS:"GET_REQUESTS",
    REJECT_A_REQUEST:"REJECT_A_REQUEST",
    ACCEPT_A_REQUEST:"ACCEPT_A_REQUEST",
    GET_RECOMENDATIONS:"GET_RECOMENDATIONS",
    CONNECT_A_RECOMENDATION:"CONNECT_A_RECOMENDATION",
    DELETE_A_RECOMENDATION:"DELETE_A_RECOMENDATION",
    SET_REQUESTS:"SET_REQUESTS",
    SET_RECOMENDATIONS:"SET_RECOMENDATIONS"
}

export default networkActionTypes