const newsPageActions={
    GET_LATEST_NEWS:'GET_LATEST_NEWS',
    SEND_LATEST_NEWS:'SEND_LATEST_NEWS',
    OPEN_FULL_NEWS:'OPEN_FULL_NEWS',
    CLOSE_FULL_NEWS:'CLOSE_FULL_NEWS'
}

export default newsPageActions