const profiileActionTypes={
    EDIT_USER_DATA_START:"EDIT_USER_DATA_START",
    EDIT_USER_DATA_CANCEL:"EDIT_USER_DATA_CANCEL",
    EDIT_USER_DATA_SAVE:"EDIT_USER_DATA_SAVE",
    EDIT_USER_DATA_SUCCESFUL:"EDIT_USER_DATA_SUCCESSFUL",
    EDIT_USER_DATA_FAILURE:"EDIT_USER_DATA_FAILURE",
    SET_EDITED_USER_DETAILS:"SET_EDITED_USER_DETAILS",
    
}

export default profiileActionTypes